### ISSUE TITLE
Crash using plugins that add entities to the world tracker

### ISSUE THREAD

**Issue by J4im3x0** [CobbleSword/NachoSpigot#337]
### Observed Behavior

The server crashes when I use plugins that add entities to the world tracker (as method to display NPCs or holograms as example)

### Expected Behavior

Not crashing

### Steps To Reproduce

Using any plugin that adds entities to the world tracker

### Plugin List

[01:39:25 INFO]: Plugins (64): MEAC, PlaceholderAPI, PlugMan, DonkeyDupeFix, MAInventories, LeaderHeadsRevamped, BugFixer, ConsoleSpamFix, ChatReaction, TitleAPI, RandomTeleport, ViaVersion, NoItemRename, FawCommandChecker, CoreProtect, StoreStats, LuckPerms, ClearLag, TimedFly, spark, IllegalStack, JetsAntiAFKPro, WorldBorder, EzChat, Anti-phase, BuycraftX, Votifier, Multiverse-Core, MABukkit, FastAsyncWorldEdit, DeluxeMenus, Vault, MAHolograms, Sumo, ClientStats, MABarrier, VoteParty, MAClans, DonatorJoinPlus, PlayerVaults, MATab, WorldEdit, Essentials, JetsPrisonMines, MASigns, MarriageMaster, CrateReloaded, MineaquaNpcs, zAuctionHouseV3, TradeSystem, Lottery, WorldGuard, CombatLogX, MACollectors, EssentialsSpawn, WorldGuardExtraFlags, TitleManager, MyPet, Jobs, ProtectionStones, KOTH, WildStacker, ShopGUIPlus, WildTools

### Server Version

[01:38:22 INFO]: Checking version, please wait...
[01:38:22 INFO]: This server is running NachoSpigot version git-NachoSpigot-"28047e7" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
You are running the latest version

### Other

[crash-2022-01-25_01.32.43-server.txt](https://github.com/CobbleSword/NachoSpigot/files/7930645/crash-2022-01-25_01.32.43-server.txt)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**
